[package]
name = "advent-of-code-2015"
version = "0.1.0"
authors = ["Scotow <contact@scotow.com>"]
edition = "2021"

[dependencies]
itertools = "0.9.0"
md5 = "0.7.0"
serde = "1.0"
serde_json = "1.0"
rand = "0.8"
