[package]
name = "day-01"
version = "0.1.0"
authors = ["scotow"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { git = "https://github.com/irevoire/aoc", version = "0.1.1" }
itertools = "0.9.0"